### ISSUE TITLE
ManageMonitorNodes object has no attribute stop

### ISSUE THREAD

**Issue by fritz-smh** [Nico0084/domogik-plugin-ozwave#14]
See the trace : 

```
2015-12-09 18:33:44,907 domogik-ozwave DEBUG Calling stop additionnal method : leave 
2015-12-09 18:33:44,908 domogik-ozwave DEBUG send hbeat.end
2015-12-09 18:33:44,908 domogik-ozwave DEBUG send hbeat
2015-12-09 18:33:44,909 domogik-ozwave DEBUG normal send
2015-12-09 18:33:44,914 domogik-ozwave DEBUG xPL thread stopped
2015-12-09 18:33:44,914 domogik-ozwave DEBUG Calling stop additionnal method : stop 
2015-12-09 18:33:44,915 domogik-ozwave INFO Stopping plugin, Remove driver(s) from openzwave
ERROR Traceback (most recent call last):
  File "/opt/dmg/domogik-mq/src/domogikmq/reqrep/worker.py", line 219, in _on_mpd_message
    self.on_mdp_request(mes)
  File "bin/ozwave.py", line 142, in on_mdp_request
    XplPlugin.on_mdp_request(self, msg)
  File "/opt/dmg/domogik/src/domogik/common/plugin.py", line 645, in on_mdp_request
    self._mdp_reply_client_stop(msg)
  File "/opt/dmg/domogik/src/domogik/common/plugin.py", line 723, in _mdp_reply_client_stop
    self.force_leave()
  File "/opt/dmg/domogik/src/domogik/xpl/common/plugin.py", line 163, in force_leave
    Plugin.force_leave(self, status, return_code)
  File "/opt/dmg/domogik/src/domogik/common/plugin.py", line 937, in force_leave
    cb()
  File "/var/lib/domogik/domogik_packages/plugin_ozwave/lib/ozwave.py", line 374, in stop
    self.monitorNodes.stop()
AttributeError: 'ManageMonitorNodes' object has no attribute 'stop'

2015-12-09 18:33:45,933 domogik-ozwave INFO self._should_stop set, leave.
./start.sh : ligne 1 : 15818 Processus arrêté      /usr/bin/python bin/ozwave.py -f
fritz@ambre:/opt/dmg/domogik-plugin-ozwave$ 
```

**Comment by Nico0084** [comment]
Please try last commit "db2f71f" on develop. it should be fix.
And tell me result
PS : My Computer is too slow, so a stop.isSet() arrived before self.monitorNodes.stop() call !
I can't test with your context.
