### ISSUE TITLE
Can't add a device

### ISSUE THREAD

**Issue by jgaret** [Nico0084/domogik-plugin-ozwave#39]
I am using plugin version 0.5.3 and when I try to add a node, from the advanced tab, I get this error:

> 2017-03-28 23:00:17,907 domogik-dbmgr DEBUG ['device.params.result', '{"result": {"xpl_stats": {}, "name": "", "reference": "", "xpl": [], "xpl_commands": {}, "global": [{"type": "string", "description": "Zwave network name if refered in controller node or Openzwave Home ID", "key": "networkid"}, {"description": "Zwave node id", "max_value": 255, "min_value": 1, "key": "node", "type": "integer"}, {"description": "Zwave node instance id", "max_value": 255, "min_value": 1, "key": "instance", "type": "integer"}, {"type": "boolean", "description": "Check battery level at zwave device wakeup.", "key": "batterycheck"}], "device_type": "ozwave.battery-level_sensor-alarm_temperature-c", "description": ""}}']
2017-03-28 23:00:17,956 domogik-dbmgr DEBUG MQ Request received : <MQMessage(action=device.create, data='{u'data': {u'xpl_stats': {}, u'name': u'Detecteur Chambre Lilou', u'reference': u'FIBARO System -- FGSD002 Smoke Sensor', u'xpl': [], u'xpl_commands': {}, u'global': [{u'key': u'networkid', u'type': u'string', u'description': u'Zwave network name if refered in controller node or Openzwave Home ID', u'value': u'MyHomeId'}, {u'description': u'Zwave node id', u'max_value': 255, u'min_value': 1, u'value': u'23', u'key': u'node', u'type': u'integer'}, {u'description': u'Zwave node instance id', u'max_value': 255, u'min_value': 1, u'value': u'1', u'key': u'instance', u'type': u'integer'}, {u'key': u'batterycheck', u'type': u'boolean', u'description': u'Check battery level at zwave device wakeup.', u'value': u'n'}], u'device_type': u'ozwave.battery-level_sensor-alarm_temperature-c', u'client_id': u'plugin-ozwave.jeedom', u'description': u'Detecteur de fumee Chambre Lilou'}}')>
2017-03-28 23:00:18,073 domogik-dbmgr DEBUG ['device.create.result', '{"status": false, "reason": "An error occured while adding the device in database. Please check the file dbmgr.log for more informations"}']
2017-03-28 23:00:18,079 domogik-dbmgr ERROR Error while processing request. Message is : <MQMessage(action=device.create, data='{u'data': {u'xpl_stats': {}, u'name': u'Detecteur Chambre Lilou', u'reference': u'FIBARO System -- FGSD002 Smoke Sensor', u'xpl': [], u'xpl_commands': {}, u'global': [{u'key': u'networkid', u'type': u'string', u'description': u'Zwave network name if refered in controller node or Openzwave Home ID', u'value': u'MyHomeId'}, {u'description': u'Zwave node id', u'max_value': 255, u'min_value': 1, u'value': u'23', u'key': u'node', u'type': u'integer'}, {u'description': u'Zwave node instance id', u'max_value': 255, u'min_value': 1, u'value': u'1', u'key': u'instance', u'type': u'integer'}, {u'key': u'batterycheck', u'type': u'boolean', u'description': u'Check battery level at zwave device wakeup.', u'value': u'n'}], u'device_type': u'ozwave.battery-level_sensor-alarm_temperature-c', u'client_id': u'plugin-ozwave.jeedom', u'description': u'Detecteur de fumee Chambre Lilou'}}')>. Error is : Traceback (most recent call last):
  File "/opt/dmg/domogik-0.5.2/src/domogik/bin/dbmgr.py", line 148, in on_mdp_request
    self._mdp_reply_sensor_history(msg)
  File "/usr/lib/python2.7/contextlib.py", line 24, in __exit__
    self.gen.next()
  File "/opt/dmg/domogik-0.5.2/src/domogik/common/database.py", line 180, in session_scope
    self.__session.commit()
  File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/orm/session.py", line 874, in commit
    self.transaction.commit()
  File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/orm/session.py", line 459, in commit
    self._assert_active(prepared_ok=True)
  File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/orm/session.py", line 276, in _assert_active
    % self._rollback_exception
InvalidRequestError: This Session's transaction has been rolled back due to a previous exception during flush. To begin a new transaction with this Session, first issue Session.rollback(). Original exception was: (_mysql_exceptions.IntegrityError) (1062, "Duplicate entry '0-networkid' for key 'PRIMARY'") [SQL: u'INSERT INTO core_device_param (device_id, `key`, value, type) VALUES (%s, %s, %s, %s)'] [parameters: (6L, 'networkid', 'MyHomeId', 'string')]

**Comment by Nico0084** [comment]
Hi
Due to kind of error , I presume you use dmg 0.6 (develop) ?
It''s not a direct plugin error. There is some conflict between multi-process end time response.
Some history values record DB must be do during create device .
Check if device it''s not really created. Try  to create again it if not. 
I let issue open to link it on domogik. We are working on it to solve.....
